# Generated by Django 3.2.9 on 2021-12-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betdata',
            name='gol',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='betdata',
            name='ics',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='betdata',
            name='one',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='betdata',
            name='over',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='betdata',
            name='two',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='betdata',
            name='under',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
