# Generated by Django 3.2.9 on 2021-12-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betdata',
            name='user',
        ),
    ]
