# Generated by Django 3.2.9 on 2021-12-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='csv_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
