# Generated by Django 3.2.9 on 2021-12-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0002_remove_betdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_identifier',
            field=models.CharField(default=1, max_length=127, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_url', models.URLField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_server.user')),
            ],
        ),
        migrations.AddField(
            model_name='betdata',
            name='search_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web_server.search'),
            preserve_default=False,
        ),
    ]
